var express = require("express");
var router = express.Router();
const orderController = require("../controllers/orderController");
router.post("/user/:userId/store/:storeId", orderController.placeOrder);
router.get("/:id", orderController.viewOrder);
router.post("/:id/checkout", orderController.checkout);
router.get("/after-checkout/payment", orderController.payment);
router.post("/:id/refund", orderController.refundOrder);
router.post("/cancel-order", orderController.cancelOrderWhenTimeOut);
module.exports = router;
