var express = require("express");
var router = express.Router();
const userController = require("../controllers/userController");
router.post("/", userController.signUpUser);
router.get("/:id", userController.getUserById);
router.get("/", userController.getAllUser);
router.patch("/:id", userController.updateUser);
router.delete("/:id", userController.deleteUser);
router.post("/change-pass/:id", userController.changePass);
module.exports = router;
